### ISSUE TITLE
Need to maintain standard naming convention for html

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-user-profile-avatar#10]
Please follow standar naming convention for the html tag.

we always follow name with - instead of _(underline).

for example you have mentioned, wpupa_show_avatars in html that wrong.

at wp-user-profile-avatar-settings.php

`<fieldset>
							              <label for="wpupa_show_avatars">
							                <input name="wpupa_show_avatars" type="checkbox" id="wpupa_show_avatars" value="1" <?php echo checked($wpupa_show_avatars, 1, 0); ?> > <?php _e('Show Avatars', 'wp-user-profile-avatar'); ?>
							              </label>
							              <p class="description"><?php _e('If it is unchecked then it will not show the user avatar at profile and frontend side.', 'wp-user-profile-avatar'); ?></p>
							            </fieldset>
`

Please check all the file and wherever you have used _ for html attribute then please change it.

**Comment by ashokdudhat** [comment]
Please check above carefully and applied it if not applied then.. you can also talk with krinay.

**Comment by vijayrathod245** [comment]
I have changed all html attribute.
Could you please check it from your side.

**Comment by krinaydhanani** [comment]
This version is released. I am going to close this issue.
