### ISSUE TITLE
Image URL avatar is not set

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#101]
The image URL avatar is not set.

 Using shortcode and option.

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/bf245988-3ef1-4199-a4bd-dcda9af1a122)

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/fbf6b0ed-bdf8-4ef7-b6d6-6c5a4ffc1e80)

**Comment by krinaydhanani** [comment]
@live-aamir In this case we have to give the priority to the URL. If any user enter any URL then we will show the image from URL path. If there no any URL then we will take image from bottom.

**Comment by mistry-jignesh** [comment]
Need to check with shortcode .

[user_profile_avatar_upload] 

When I have added Image URL path then it should be set with profile image.

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/d6d45319-1ad1-4cbd-aaf1-ac59b16602ee)





**It should be set image as backend side.**

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/f12c4031-f43d-49e4-a0e5-f62a24c86d22)



![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/496b2a7b-7bb5-49d3-ac41-1234cda4df09)

**Comment by mistry-jignesh** [comment]
I have checked the Image URL issue. Now the image URL avatar is saved.
It is working fine. So I closed the issue.
