### ISSUE TITLE
load fontawesome locally for security

### ISSUE THREAD

**Issue by live-aamir** [wpeventmanager/wp-user-profile-avatar#117]
![Screenshot_1](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/49248762/0b901b32-f9b9-4542-b6f0-cac5ab07152e)

**Comment by mistry-jignesh** [comment]
I have verified issue with help of Kaushik. Now it is working fine.
So I closed the issue.
![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/b980fab8-82a8-4f19-b391-0b1c15145abd)
