### ISSUE TITLE
Unexpecated Output error message display on the page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#121]
When trying to activate the User profile avatar addon the below error message displays on the screen.
Need to check it.

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/55d70cb5-609d-4568-bc75-c5eaade9dba1)

**Comment by RavindraSingh2001** [comment]
@mistry-jignesh This issue is fixed in the issue #120

**Comment by mistry-jignesh** [comment]
This issue is covered in the issue #120. Now this issue is working fine.
So I closed the issue.
