### ISSUE TITLE
code review by Rita

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-user-profile-avatar#123]

**Comment by ritakikani** [comment]
![image](https://github.com/user-attachments/assets/8bffe49c-b974-4aee-bbc5-109b67f27fe0)

**Comment by ritakikani** [comment]
Remove this

![image](https://github.com/user-attachments/assets/dfff8484-1ce7-4d09-b380-8c7144a3a432)

**Comment by ritakikani** [comment]
![image](https://github.com/user-attachments/assets/b110de31-bfa1-4395-860f-4b903658a389)

**Comment by ritakikani** [comment]
Why this much code lines are commented? not needed? then please delete it.

![image](https://github.com/user-attachments/assets/727c6799-d5ec-4238-8db5-e20b5b01c498)

**Comment by ritakikani** [comment]
Why so many lank lines are in code? please remove it.

![image](https://github.com/user-attachments/assets/62f50d8f-8614-4fe8-babf-845774582c66)

**Comment by ritakikani** [comment]
again, so many lines of code are commented. if not used anymore then please delete it.

![image](https://github.com/user-attachments/assets/58060404-ce11-47f0-9d7e-f7fd839e9fe4)

**Comment by ritakikani** [comment]
function declare in template file? please delete these functions from here and put them in functions.php file.

![image](https://github.com/user-attachments/assets/c12b5987-06d2-4fd5-ac62-743fbb2e3115)

**Comment by ritakikani** [comment]
Again the same thing, functions inside template file.

![image](https://github.com/user-attachments/assets/c1dd5585-99b5-40d7-99b2-95b9e4232610)

**Comment by ritakikani** [comment]
Class inside template file? please move it outside template folder

![image](https://github.com/user-attachments/assets/cde7bea3-6268-4800-a83f-bc19c35a5a56)

**Comment by ritakikani** [comment]
![image](https://github.com/user-attachments/assets/9eae5052-fc90-4c0e-a193-e1190e746b97)

**Comment by ritakikani** [comment]
remove this commented code

![image](https://github.com/user-attachments/assets/ee4f6417-939c-45e5-b843-d729b98735bb)

**Comment by ritakikani** [comment]
remove this code if not using now

![image](https://github.com/user-attachments/assets/c1c0195a-b5e9-4c3f-84fb-0c40065b10ee)

**Comment by ritakikani** [comment]
same like above, not using this now then please remove it.

![image](https://github.com/user-attachments/assets/556e47f2-acdf-4a46-8c83-2ba12adf382c)

**Comment by ritakikani** [comment]
remove this

![image](https://github.com/user-attachments/assets/b56a4a48-ccce-48b5-ba35-4bc3a933f70c)

**Comment by ritakikani** [comment]
create min.js file for this and use min file

![image](https://github.com/user-attachments/assets/784640d7-f8b4-49ab-948c-24f993df1e7d)

**Comment by ritakikani** [comment]
remove extra blank line

need proper indentation
need function description

![image](https://github.com/user-attachments/assets/05fb99c9-3853-41ec-a810-496e86da0968)

**Comment by ritakikani** [comment]
these should be capital

![image](https://github.com/user-attachments/assets/13e290c8-8a1b-45d6-9c7e-04622dd26407)

**Comment by ritakikani** [comment]
remove this if not used

![image](https://github.com/user-attachments/assets/13122235-238b-404e-94cb-ed838d39a4e0)

**Comment by ritakikani** [comment]
delete it if not used

![image](https://github.com/user-attachments/assets/fc4081c7-5394-430f-821e-5a0e427f1a26)

**Comment by ritakikani** [comment]
Class inside template ? 

please follow our coding and file structure

![image](https://github.com/user-attachments/assets/64dee335-e9c1-4040-8808-63a530679daa)

**Comment by ritakikani** [comment]
functions inside template file ? please correct it.

![image](https://github.com/user-attachments/assets/c40dfd78-0ba0-4ea1-9b0b-f40aaef0d708)

**Comment by ritakikani** [comment]
remove commented code if not required and please remove all functions from template file

![image](https://github.com/user-attachments/assets/2c6d7a79-5186-4564-966b-91c887fa28c2)

**Comment by ritakikani** [comment]
again functions inside template file

![image](https://github.com/user-attachments/assets/c053be4d-ff26-4aaa-8a4c-d550676a44ac)

**Comment by ritakikani** [comment]
again class inside template file

![image](https://github.com/user-attachments/assets/6a379b66-f698-4103-8175-5361a316c3a6)

**Comment by ritakikani** [comment]
rename file name according to our structure, if possible then please move all simple functions in functions.php file

![image](https://github.com/user-attachments/assets/6a94bc7c-ea0b-4812-8cd5-1fdba8f16e0e)

**Comment by ritakikani** [comment]
delete this if not needed

![image](https://github.com/user-attachments/assets/b1172c0b-371e-468a-8319-a22502a0dd78)

**Comment by ritakikani** [comment]
add comment before declare each function

![image](https://github.com/user-attachments/assets/7b2e6e46-6c4a-44a4-b273-099c12ec7732)

**Comment by ritakikani** [comment]
Change only in min.js file? 

You must need to do same change in .js file then you can minify code and put code in min.js. But code in both file must be same.

![image](https://github.com/user-attachments/assets/59b5158f-16a1-43ed-b053-4e7814abe2a4)

**Comment by ritakikani** [comment]
@RHSRSK , please move these all functions in functions.php file. inside "include" folder all class-files will be there.

**Also please write comment proper for all function (must need to write how and when function used - do not write just function name)**

![image](https://github.com/user-attachments/assets/cff1040b-bd2d-4b66-ba2d-d46e5083bcff)

**Comment by ritakikani** [comment]
@RHSRSK , you just move all files from template to include folder, while you move all simple function in functions.php file.

![image](https://github.com/user-attachments/assets/cf645bd5-428c-4f7f-988a-9cad2ddefc24)

**Comment by ritakikani** [comment]
write this line at the end of the file

![image](https://github.com/user-attachments/assets/912c4925-8f49-4b3b-8918-31650d194c8d)

**Comment by ritakikani** [comment]
again simple functions created in  1 file and that file is inside template folder.
Please delete functions from this file and move them in functions.php file

![image](https://github.com/user-attachments/assets/2d67d078-3780-4fe3-9a65-543ac79b146e)

**Comment by ritakikani** [comment]
I already mention this in previous comment to transfer this file in include folder

![image](https://github.com/user-attachments/assets/9e6393bf-8f32-4488-88e3-300fc942f2fe)

**Comment by ritakikani** [comment]
Please write proper comment everywhere you declare function
Also please write comment proper for all function (must need to write how and when function used - do not write just function name)

![image](https://github.com/user-attachments/assets/558af95a-380b-48ad-81b5-4300d10ed211)

**Comment by RHSRSK** [comment]
> @RHSRSK , please move these all functions in functions.php file. inside "include" folder all class-files will be there.
> 
> **Also please write comment proper for all function (must need to write how and when function used - do not write just function name)**
> 
> ![image](https://private-user-images.githubusercontent.com/25837982/349897401-cff1040b-bd2d-4b66-ba2d-d46e5083bcff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTY2MzAsIm5iZiI6MTcyMTI5NjMzMCwicGF0aCI6Ii8yNTgzNzk4Mi8zNDk4OTc0MDEtY2ZmMTA0MGItYmQyZC00YjY2LWJhMmQtZDQ2ZTUwODNiY2ZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA5NTIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNGMwNGNmYTgxYTE2NjIwYzk5MmYyNWI3NTBiMGY2NWU5OThkMzNhMGU4ZmFkZTI1ZDFhYzRjNDUzOTU0NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UQn-j85pourZ_WpngGNP6JwCxBlgcT-x_nYw3sGQRhI)


Added comments before the functions in all the files
![image](https://github.com/user-attachments/assets/7d472e54-efb4-4b9e-a585-60c852ee7229)

**Comment by RHSRSK** [comment]
> @RHSRSK , you just move all files from template to include folder, while you move all simple function in functions.php file.
> 
> ![image](https://private-user-images.githubusercontent.com/25837982/349897912-cf645bd5-428c-4f7f-988a-9cad2ddefc24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDY5MzMsIm5iZiI6MTcyMTMwNjYzMywicGF0aCI6Ii8yNTgzNzk4Mi8zNDk4OTc5MTItY2Y2NDViZDUtNDI4Yy00ZjdmLTk4OGEtOWNhZDJkZGVmYzI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDEyNDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyZTVkNTNjNjM1YzE4N2U2ZjEyODVhNDNjMmUwNjU3ODhlZGE2NjVhYWI5MDFiMTQzZDZjNDk4ODc1M2ExYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rtAsD4ug0rdxGzRw72z6XrkqrXjWVkmwX0XGfbq2XHk)

![image](https://github.com/user-attachments/assets/65fa0154-4696-4df4-bbe5-614c9c7aa9af)
Move files to includes folder and set add the action and filter in class

**Comment by RHSRSK** [comment]
> write this line at the end of the file
> 
> ![image](https://private-user-images.githubusercontent.com/25837982/349898173-912c4925-8f49-4b3b-8918-31650d194c8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDY5MzMsIm5iZiI6MTcyMTMwNjYzMywicGF0aCI6Ii8yNTgzNzk4Mi8zNDk4OTgxNzMtOTEyYzQ5MjUtOGY0OS00YjNiLTg5MTgtMzE2NTBkMTk0YzhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDEyNDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3ZmUwM2QyZGE0ZDNkY2M1YjhhYjRlZGNjMjE3MzEzYjZmZGFlZWUyNGY3Yzc2ZDkzMmI1OGY1Mzc1NzA1NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g6msbl3QQKqcuG-u2Cop_11xyWdXmQWSxgpQKcVq-co)

![image](https://github.com/user-attachments/assets/34ab9e30-0f61-4a87-ae43-62f349a1a875)

Add the line in last

**Comment by RHSRSK** [comment]
> again simple functions created in 1 file and that file is inside template folder. Please delete functions from this file and move them in functions.php file
> 
> ![image](https://private-user-images.githubusercontent.com/25837982/349898939-2d67d078-3780-4fe3-9a65-543ac79b146e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDY5MzMsIm5iZiI6MTcyMTMwNjYzMywicGF0aCI6Ii8yNTgzNzk4Mi8zNDk4OTg5MzktMmQ2N2QwNzgtMzc4MC00ZmUzLTlhNjUtNTQzYWM3OWIxNDZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDEyNDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxOGU1MWU0OTI4M2Y0NTllNDJmMDJlMjNiYmZiZTFkMWRiMDY2ZTg0NzhiYTA1OTE5YTUxODY5N2YzNjU3NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e0x5UrHuppqBu5mbJvZxMcktOwhpPaCqVAGer4I44_M)

Moved all the functions in wp-user-profile-avatar-functions.php files and remove wp-user-list.php file

**Comment by RHSRSK** [comment]
> I already mention this in previous comment to transfer this file in include folder
> 
> ![image](https://private-user-images.githubusercontent.com/25837982/349899230-9e6393bf-8f32-4488-88e3-300fc942f2fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDY5MzMsIm5iZiI6MTcyMTMwNjYzMywicGF0aCI6Ii8yNTgzNzk4Mi8zNDk4OTkyMzAtOWU2MzkzYmYtOGYzMi00NDg4LTg4ZTMtMzAwZmM5NDJmMmZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDEyNDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMmNlNmQ1OWQzMWQ0MjNiZWIzNDQ3YTkxZGRiZjdhOWVjNGMxYTYxZDg1NzEwYjk2MjA0ZDE2OTBmMTEyYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hd1fd1NKCw6QB57xBLbBIXJM33zyPIbndDje9Lkcbqg)

Moved all the class file in includes folder

**Comment by RHSRSK** [comment]
> Please write proper comment everywhere you declare function Also please write comment proper for all function (must need to write how and when function used - do not write just function name)
> 
> ![image](https://private-user-images.githubusercontent.com/25837982/349899454-558af95a-380b-48ad-81b5-4300d10ed211.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDY5MzMsIm5iZiI6MTcyMTMwNjYzMywicGF0aCI6Ii8yNTgzNzk4Mi8zNDk4OTk0NTQtNTU4YWY5NWEtMzgwYi00OGFkLTgxYjUtNDMwMGQxMGVkMjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDEyNDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmZjBhZTUzYzQ1YjllZDYxYmEwNzJjYjQyNTYyZDkwMTcyN2MyMzYyZmM3NGIxZDEzM2I0ZmRiMWU0ZjY2OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-PIfdzjb7D-KYtMdcN5_fgdcOYXpDrZCTT06EnPdiqw)

![image](https://github.com/user-attachments/assets/cdc49283-1216-4445-89ff-879dee62c332)
Comments are added before functions in all files

**Comment by mistry-jignesh** [comment]
I have verified the issue. Now this issue is working fine.
So I closed the issue.
