### ISSUE TITLE
WP User profile avatar : Default Avatar - By default Blue user icon is not visible

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#126]
WP User profile avatar: Default Avatar - The blue user icon is not visible

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/1cf74ac9-cb40-4bd3-8b94-caea004e3f31)

**It should be displayed like the below icon.**

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/97e05215-949c-4564-9c79-e52675197b0e)

**Comment by RHSRSK** [comment]
I think it's working 
[Plugins ‹ Event Organizer — WordPress (1).webm](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/126595044/914bc940-51d1-44a1-b742-3ccf11c32be8)

**Comment by mistry-jignesh** [comment]
I have verified issue in the new local setup. Now bydefault blue user icon is visible.
This issue is working fine.

![image](https://github.com/user-attachments/assets/625e624e-d10a-454b-9f79-6999a974ee6e)

So I close d the issue.
