### ISSUE TITLE
Post page : Admin profile image is missing 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#127]
If the admin post page view in the organizer or subscriber account then the Admin profile image is missing.

![image](https://github.com/user-attachments/assets/f58e46d9-695a-4aaf-a9a3-65ab193ff5f1)

**Comment by RHSRSK** [comment]
If I used wordpress default theme it's display
![image](https://github.com/user-attachments/assets/b53fd5a2-73e2-473c-80a6-dfa4d6d4bc3e)

In event-listing theme its not display

**Comment by RHSRSK** [comment]
![image](https://github.com/user-attachments/assets/956999ee-4d9c-4628-9a3a-310049403808)
Need to enable Show avatar check box and then it's display the avatar 
![image](https://github.com/user-attachments/assets/2f3e647a-a5b9-4e2f-be28-52fd00d971b9)

**Comment by mistry-jignesh** [comment]
I have verified this issue. This issue is fixed.
Admin profile image is visible. So I closed the issue.
