### ISSUE TITLE
Delete comment - Post is unable to delete

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#129]
Delete comment - Post is unable to delete.

**Comment by RHSRSK** [comment]
Delete comment setting for posts is working fine on front end as well as on backend
[Edit Post “Test Post” ‹ MySite — WordPress.webm](https://github.com/user-attachments/assets/20a9ba34-77da-446d-b2ec-9ce1f9e75c4f)

**Comment by mistry-jignesh** [comment]
I have checked the issue. Now the post comment is deleted.
It is working fine. So I closed the issue.
