### ISSUE TITLE
Deleted comment from the event then also 1 count is display

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#131]
Deleted comment from the event then also 1 count is displayed.

Also need to check Organizer,Venue.

![image](https://github.com/user-attachments/assets/e96f9a74-0202-491d-b001-ff0ff737ae03)

**Comment by mistry-jignesh** [comment]
I have verified this issue. Issue facing in the organizer and venue.
Comment is not deleted.

**Comment by officialnishantdhiman** [comment]
@mistry-jignesh This is working fine.

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now after deleting a comment count is removed.

It is working fine.

![image](https://github.com/user-attachments/assets/1a002589-0263-432d-9b71-8d1a32fb91e9)

So I closed the issue.
