### ISSUE TITLE
Commet adding issue 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#132]
- Media : From the backend /Frontend not adding comments.

- Event/Venues/Product/Page : From the front side not adding comments.

**Comment by RHSRSK** [comment]
[Edit Event “Innovative Tech Webinar” ‹ MySite — WordPress.webm](https://github.com/user-attachments/assets/f72dce35-98a3-44d4-a3cc-7473f04ed088)
It's working fine Please make sure Discussion and Comment Screen Option is on to see the comment on backend as well as front end

**Comment by mistry-jignesh** [comment]
I have verified this issue but still frontend side facing an issue.

**Event/Venues/Product/Page** : From the front side not adding comments.

Please check it.

**Comment by officialnishantdhiman** [comment]
@mistry-jignesh This is working fine.

**Comment by mistry-jignesh** [comment]
I have verified this issue. This issue is working fine.
So I closed the issue.
