### ISSUE TITLE
Default avatar image issue

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-user-profile-avatar#136]
After installing our plugin, in settings->discussion->Default avatar, I am getting all default avatar image same.

![image](https://github.com/user-attachments/assets/27b19ca8-c36e-412b-b722-53c67d889729)

**Comment by mistry-jignesh** [comment]
After installing the UPA plugin, the default avatar section option same image visible in all options.

![image](https://github.com/user-attachments/assets/c858d985-d5c8-49d4-93f2-92b06033c966)

Need to check again .

**Comment by mistry-jignesh** [comment]
I have verified this issue. This issue is fixed.
Now the default avatar image is working fine.

![image](https://github.com/user-attachments/assets/a2345246-b316-4830-8af4-973062dd38f8)

So I closed the issue.
