### ISSUE TITLE
User Profile is not update from User Profile Avatar Settings Page

### ISSUE THREAD

**Issue by RHSRSK** [wpeventmanager/wp-user-profile-avatar#137]
![14 08 2024_18 42 22_REC](https://github.com/user-attachments/assets/3bfc0389-90a8-44d5-a57f-c240a95c425a)

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now User Profile is updated from the User Profile Avatar Settings Page.
So I  closed the issue
