### ISSUE TITLE
Default Avatar : Change Gravatar Logo to Mystery Man option

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#138]
Last I have select  Gravatar Logo option.
Now I have update plugin 1.0.5 version.
![image](https://github.com/user-attachments/assets/600b6cda-8e88-406b-9b01-465e1af145d1)
Go to WP user profile avatar >> Default  avatar option
Here  change Gravatar Logo to Mystery Man option.

**Comment by mistry-jignesh** [comment]
Currently, enables to verify this because all options set one default image.
2 servers facing the same issue.

![image](https://github.com/user-attachments/assets/468841c4-3e8b-4944-8427-cfad5a9c3768)

**Comment by officialnishantdhiman** [comment]
@mistry-jignesh Issue resolved on https://github.com/wpeventmanager/wp-user-profile-avatar/issues/136

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now gravatar logo is not changed after update plugin.
It is working fine. So I closed the issue.
