### ISSUE TITLE
After updating plugin user profile image as set Mystery Man image

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#139]
After updating plugin user profile image as set Mystery Man image.

![image](https://github.com/user-attachments/assets/65b67c65-a88f-406c-a80b-31e4787c4eb9)

**Comment by RHSRSK** [comment]
This issue is solved within this issue https://github.com/wpeventmanager/wp-user-profile-avatar/issues/140
![image](https://github.com/user-attachments/assets/da524a29-42b9-4f76-8300-eb71f2d7a671)

**Comment by mistry-jignesh** [comment]
I have verified the issue. This issue is fixed.
So I closed the issue.
