### ISSUE TITLE
Comment :  Admin profile is not display

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#140]
Comment :  Admin profile is not display.

![image](https://github.com/user-attachments/assets/a11d9c2f-7080-4185-8e84-9b57f57f7a0d)

**Comment by RHSRSK** [comment]
Admin Profile pic is now display 
![image](https://github.com/user-attachments/assets/bc53f230-e69b-4b26-9e78-78a763c0374a)

**Comment by mistry-jignesh** [comment]
I have verified this issue. This issue is fixed.
Now admin profile is visible.So I closed the issue.
