### ISSUE TITLE
Error message is available in the export registration sheet

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#145]
An error message is available in the export registration sheet

Export sheet from the backend registration section.

![image](https://github.com/user-attachments/assets/b8d030f4-fcb2-461b-a0d7-7d716c002e6a)

[registrations (1).csv](https://github.com/user-attachments/files/17093017/registrations.1.csv)

**Comment by RHSRSK** [comment]
This issue is resolved after update User Profile Avatar Plugin

**Comment by mistry-jignesh** [comment]
Now check the issue with the version. It is working fine.

![image](https://github.com/user-attachments/assets/362277ae-8483-4c45-b119-6018f6901b45)

So I closed the issue.
