### ISSUE TITLE
Default size of the avatar image option

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-user-profile-avatar#16]
Assign default size to the avatar when there is no size given it. Admin can set default avatar size.

<img width="421" alt="Screenshot 2020-05-24 at 15 55 37" src="https://user-images.githubusercontent.com/15089059/82755905-083d8380-9dd7-11ea-9dcd-56de8e2c6437.png">

**Comment by krinaydhanani** [comment]
This issue still not fixed. I can not see any setting regarding the size option.

**Comment by pooja-pragda** [comment]
Default size to the avatar when there is no size given it. - fixed
Also, the admin can set the default avatar size.

![image](https://user-images.githubusercontent.com/76870773/105020136-ef23ca00-5a6c-11eb-8baf-9e06ca57dd56.png)

**Comment by pooja-pragda** [comment]
Fields rearranged.

![image](https://user-images.githubusercontent.com/76870773/105124738-c9e09b80-5b00-11eb-87e0-539224fca1fc.png)

**Comment by mistry-jignesh** [comment]
This issue is resolved . Now Admin is able to set default avatar size.

**Comment by krinaydhanani** [comment]
@mistry-jignesh Please verify it.

**Comment by mistry-jignesh** [comment]
When I have clicked on the WP user profile avatar icon and filled up details. Now I have  changed avatar size from profile setting page and values set as "250" then their is no effect display on the avatar size.

![image](https://user-images.githubusercontent.com/75515088/106126583-8b438480-6183-11eb-820f-fd27d21eee40.png)

![image](https://user-images.githubusercontent.com/75515088/106127411-8cc17c80-6184-11eb-9ab8-563e024aa20b.png)

**Comment by pooja-pragda** [comment]
If you set size - Original then it always returns original size of image.
![image](https://user-images.githubusercontent.com/76870773/133991805-2d0562b6-9ba8-4fa6-8fea-4a49d7f5ccfe.png)
