### ISSUE TITLE
Compatibility with bbPress

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-user-profile-avatar#17]
Automatically adds avatar support to bbPress (2.3+) user profiles if bbPress is activated.

for more info: https://wordpress.org/plugins/basic-user-avatars/

**Comment by mistry-jignesh** [comment]
Right user profile picture is not display in the forum.

![image](https://user-images.githubusercontent.com/75515088/106101402-dcdc1700-6163-11eb-877d-e4610c40a588.png)

**Comment by pooja-pragda** [comment]
Even plugin is not displaying user profile on the forum page.

**Comment by mistry-jignesh** [comment]
Verified this issue .Now this issue is working fine.

Now compability with bbpress.

![image](https://user-images.githubusercontent.com/75515088/172349441-a98c7d53-88fc-4cf6-894e-c23396fda990.png)
