### ISSUE TITLE
Elementor Element Tag shortcode

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-user-profile-avatar#22]
You need to create an Element Tag for the Elementor page builder plugin for the existing all the shortcodes- Two shortcodes.

You can find all the shortcodes (Two) from this file: https://github.com/wpeventmanager/wp-user-profile-avatar/blob/master/shortcodes/wp-user-profile-avatar-shortcodes.php

**Comment by pooja-pragda** [comment]
All elementor shortcodes here & also works fine.
![image](https://user-images.githubusercontent.com/76870773/133993744-fc4261f0-d991-4e13-bc27-095adf3e8641.png)
