### ISSUE TITLE
Author box with social media profile link 

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-user-profile-avatar#23]
Shortcode represents an author box with a social profile link, designation, and short info about the author.

Ref: https://wordpress.org/plugins/simple-author-box/

Need to make a template (template used in shortcode) which the user can override.

**Comment by krinaydhanani** [comment]
[authorbox_social_info] 

We have to make this shortcode dynamically like it is working with other shortcodes.

**Comment by pooja-pragda** [comment]
author box with a social profile link, designation, and short info about the author. - fixed.

![image](https://user-images.githubusercontent.com/76870773/105346031-0698b980-5c0b-11eb-84f4-364b60231689.png)

![image](https://user-images.githubusercontent.com/76870773/105346307-6abb7d80-5c0b-11eb-9ffe-399261e8b2cf.png)

**Comment by mistry-jignesh** [comment]
When I have added short code "[authorbox_social_info]" and view Click on the "View page" link then 
author box is display blank and social profile link does not display on the screen. 
Also other error message is display on the page. This issue is not resloved. 

![image](https://user-images.githubusercontent.com/75515088/105680091-49ada200-5f15-11eb-9e15-379974139084.png)

**Comment by pooja-pragda** [comment]
If the attached settings are not filled by a user then the author box will display blank and also social profile link does not display on the screen.

![image](https://user-images.githubusercontent.com/76870773/105844959-0a0fb480-6000-11eb-9239-c5362e6690b4.png)

**Comment by mistry-jignesh** [comment]
I have filled all details related social media .This information are properly display but user profile image is not showing .

Please check it.

![image](https://user-images.githubusercontent.com/75515088/105980653-26245c00-60bb-11eb-8c2e-28e77d6c1f94.png)

**Comment by mistry-jignesh** [comment]
Verified this issue . User profile image is not showing on the page.

So issue is present.

![image](https://user-images.githubusercontent.com/75515088/172138958-662a379e-797b-4402-ab39-3414990a078d.png)

**Comment by mistry-jignesh** [comment]
Verified this issue. Now this issue is fixed and working.

Author with social media profile link is display.

So I closed the issue.
