### ISSUE TITLE
file size control

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-user-profile-avatar#29]
We can give option from the settings that user can control file size. 

we can provide combobox and there we can list some option for the file size and default we can set one option.

https://wordpress.org/support/topic/upload-control/

**Comment by sahupooja93** [comment]
User can upload and control file size from admin section submenu=>WP Control File Size

**Comment by krinaydhanani** [comment]
@Priya-Goenka please provide suitable text for this label.

**Comment by pooja-pragda** [comment]
#29 file size control -  Avatar file size restriction limit set.

![image](https://user-images.githubusercontent.com/76870773/105162527-c1a45280-5b38-11eb-8dac-5a5460c09fbc.png)

Implementation of media selection popup with current user images 

![image](https://user-images.githubusercontent.com/76870773/105162797-15af3700-5b39-11eb-8152-b1d0dd417a68.png)

**Comment by mistry-jignesh** [comment]
Right now I am not able to upload file size > 40 .It is display error message .

I am try to upload file size is 83.6 MB . This image is not upload.

Please correct it.

![image](https://user-images.githubusercontent.com/75515088/105676109-10befe80-5f10-11eb-8323-963221d458f0.png)

**Comment by mistry-jignesh** [comment]
Verified this issue. Now this issue is fixed & working .

Validation message is display when upload the more than select size.

So I closed the issue.
