### ISSUE TITLE
Restrict access to Media Library

### ISSUE THREAD

**Issue by sahupooja93** [wpeventmanager/wp-user-profile-avatar#30]
Subscribers and other users Can't able to access  upload their avatar / profile picture in my Media Library.
https://wordpress.org/support/topic/restrict-access-to-media-library/

**Comment by sahupooja93** [comment]
Restrict access to Media Library issue Resolved, Subscribers and other users can only see/select own media, They Can't access Administrator  Media Library

**Comment by krinaydhanani** [comment]
If I select the role rather then contributor or subscriber then I can not access any media.

**Comment by sahupooja93** [comment]
please cheack

**Comment by krinaydhanani** [comment]
Now it's perfectly working fine. Now only the admin can see all the user media and users can see only them media.

**Comment by pooja-pragda** [comment]
Now for all user roles including contributor & subscriber access own media only. & all user roles can update their profile avatar.

**Comment by krinaydhanani** [comment]
Yes now, this issue is fixed.
