### ISSUE TITLE
Need to fix the image issue.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-user-profile-avatar#31]
I can not see the proper image on the All user page.

![image](https://user-images.githubusercontent.com/35419531/97705172-e07ed580-1a70-11eb-9669-c500f978007d.png)

**Comment by siddharthgotawala** [comment]
I have verified. Image is looking fine

**Comment by krinaydhanani** [comment]
This will happen when the user select the Crop thumbnail to exact dimensions (normally thumbnails are proportional) option from the WordPress setting.

@Priya-Goenka Please maintain these things to the doc so users will understand easily.

![image](https://user-images.githubusercontent.com/35419531/97840510-fa9afc80-1c98-11eb-926a-7c20c1f801bf.png)

**Comment by Priya-Goenka** [comment]
Is this needed to be added in the doc?
Isn't it the feature of Wordpress?

**Comment by mistry-jignesh** [comment]
Verified this issue.  Enable option - Crop thumbnail to exact dimensions (normally thumbnails are proportional) option from the WordPress setting.

Now user profile image are display proper.

![image](https://user-images.githubusercontent.com/75515088/172323002-c56c08f0-869c-4c3b-bdc0-77ad9359a0e2.png)


So I closed the issue.
