### ISSUE TITLE
Writer the label with proper text.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-user-profile-avatar#33]
Writer the label with proper text.

WpUserNameChange  - > WP Username Change  

![image](https://user-images.githubusercontent.com/35419531/97707649-d068f500-1a74-11eb-8849-e7d2526d8d2f.png)

**Comment by krinaydhanani** [comment]
The label changed now it's lool proper label.

**Comment by krinaydhanani** [comment]
WP Username Change  - > WP Username Change

![image](https://user-images.githubusercontent.com/35419531/106094626-5110bd80-6158-11eb-86ea-c3727f552048.png)

**Comment by pooja-pragda** [comment]
the setting is removed/rearranged.

**Comment by pooja-pragda** [comment]
![image](https://user-images.githubusercontent.com/76870773/134149857-230e7c19-ae9f-4b0b-ad0c-72806fdf5ae6.png)
