### ISSUE TITLE
Please remove the user fields when plugin is uninstalled

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-user-profile-avatar#34]
There are 3 fields that left in the user database table after the plugin is uninstalled.

_wpupa_attachment_id
_wpupa_default
_wpupa_url

Could you please provide a solution to remove these fields and perform a clean uninstall when the plugin is deleted.

Thank you.

**Comment by mistry-jignesh** [comment]
This issue is resolved . After uninstalled this plugin these table are removed.

**Comment by krinaydhanani** [comment]
Yes, this table is removed after deleting the addon.
