### ISSUE TITLE
Need to improve WP User Profile Avatar org banner.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-user-profile-avatar#35]
Need to improve the WP User Profile Avatar org banner because the current banner does not look good. 

https://wordpress.org/plugins/wp-user-profile-avatar/

![image](https://user-images.githubusercontent.com/35419531/103456559-53305980-4d1d-11eb-99a7-c17ce4981a2d.png)

**Comment by mistry-jignesh** [comment]
Now WP User Profile Avatar org banner is looking better . It is approved by @krinaydhanani .

So I closed the issue.
