### ISSUE TITLE
dynamic shortcode not working

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-user-profile-avatar#36]
https://wordpress.org/support/topic/dynamic-shortcode-not-working-3/

Pls check above it working or not.. if not working then pls fix it.

**Comment by pooja-pragda** [comment]
There is no need `<?php` inside php code.
use ` user_id="'.get_current_user_id().' "` to get current user profile.

echo do_shortcode('[user_profile_avatar user_id="<?php $user->id ?>" size="original" align="aligncenter" link="image" target="_blank"]'. $user->display_name .'[/user_profile_avatar]');

**Comment by mistry-jignesh** [comment]
Right now one warning message is display .

![image](https://user-images.githubusercontent.com/75515088/105974471-f32a9a00-60b3-11eb-9633-19cb8d50e21a.png)

**Comment by mistry-jignesh** [comment]
Now this error message is not shown.
