### ISSUE TITLE
Need to fix extra tooltip issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#38]
When put mouse on the user profile icon then there are two tooltip is display.

This issue is found at formus,Topics,replies, emails section.

![image](https://user-images.githubusercontent.com/75515088/106097477-63d9c100-615d-11eb-84d6-737c4908b788.png)

**Comment by siddharthgotawala** [comment]
Please remove title attribute from the link

**Comment by mistry-jignesh** [comment]
Still this issue is not resolved.

Please check image.

![image](https://user-images.githubusercontent.com/75515088/106579669-f7006580-6566-11eb-9fd6-bd80c0095daa.png)

**Comment by pooja-pragda** [comment]
![image](https://user-images.githubusercontent.com/76870773/106858909-5934a400-66e8-11eb-91e9-a19ec37f01f1.png)
