### ISSUE TITLE
Code is availabel 2 times in the page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#43]
Go to backend 

Pages > Click on the User profile avatar icon.

![image](https://user-images.githubusercontent.com/75515088/172548644-d141fe0a-2aba-4b0f-a99c-dce59119ae85.png)

Fill up user profile avatar details and click on the insert shrotcode.

Here in the page code is availabel 2 times .

(https://user-images.githubusercontent.com/75515088/172548127-7696b5ae-78bb-42ce-8da8-75b52b480595.p
![image](https://user-images.githubusercontent.com/75515088/172549119-767ec540-22a2-4dfb-bfc9-5b604b603319.png)

Same issue is face in the upload avatar option. When click on the upload avatar option then code is availabel 2 times in the page

![image](https://user-images.githubusercontent.com/75515088/172552395-3ebfdb24-fc50-4c15-9af1-9e984b816acf.png)

**Comment by RHSRSK** [comment]
This issue is same as #85 and It is solved there

**Comment by mistry-jignesh** [comment]
This issue is covered in the issue  #85. So I closed the issue.
