### ISSUE TITLE
Event details Page  - User Profile Avatar image not visible

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#47]
First add user profile avatar image as below option.

![image](https://user-images.githubusercontent.com/75515088/183827821-11269257-5fb8-4156-b6aa-52ec72d588a7.png)

Here User Profile Avatar image is added properly but on the event details page this user profile avatar image is missing.

![image](https://user-images.githubusercontent.com/75515088/183828148-c5b86234-af0a-4601-be9f-2e123f0ee154.png)

**Same issue with upload image option.**

Check this issue in the bbpress & buddy press plugin.

![image](https://user-images.githubusercontent.com/75515088/183830943-dc17e397-d313-4ccc-bbe1-5d9da0778dcf.png)

**Comment by ritakikani** [comment]
This is working fine now,

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/25837982/6d63a938-4329-4513-a066-cf5d4da66de2)


![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/25837982/e2c2bc2e-871a-4f7b-9af7-7c57b7c384af)

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this issue is fixed.
So I closed the issue.
