### ISSUE TITLE
Backend - Disable all default gravatar and set own custom default avata

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#48]
Go to Users > Profile > Settings > Check mark on the  - **Disable all default gravatar and set own custom default avatar**

I have enable and disable this option but there is no effect is availabel for this option.

![image](https://user-images.githubusercontent.com/75515088/183836695-0f680aed-df1d-4dbf-b113-bd75bf89f6df.png)

**Comment by vijayrathod245** [comment]
It's working fine, As I checked.

**Comment by mistry-jignesh** [comment]
I have verified this issue.  I have disable this option.
This issue is working. So I closed the issue.
