### ISSUE TITLE
User profile avatat  - Image URL field - If adding special symbol then sucessfully message is display

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#49]
If adding special symbol then sucessfully message is display.

![image](https://user-images.githubusercontent.com/75515088/183862730-a6f72d2e-22c4-4b4e-93f8-85065ab855ab.png)

**Comment by ritakikani** [comment]
@mistry-jignesh , yes, because we will not put any validation like you can put only alphabets, because some url may special characters also.

**Comment by mistry-jignesh** [comment]
As per @ritakikani :  We will not put any validation like you can put only alphabets, because some URL may have special characters also. So I closed the issue.
