### ISSUE TITLE
Elementor - Wp user profile avatar author box - User profile avatar image is missing

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#52]
Wp user profile avatar author box - User profile avatar image is missing. 

![image](https://user-images.githubusercontent.com/75515088/183889794-9c4d64a7-479b-40c2-ad3c-83a2e80529fd.png)

![image](https://user-images.githubusercontent.com/75515088/183889099-d2cf4660-32f0-443f-8650-3beb5a9ae05a.png)

**Comment by vijayrathod245** [comment]
I checked it, and it's working fine.
