### ISSUE TITLE
Wp user profile avatar box need to remove extra space & add proper label for box

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#53]
Wp user profile avatar box need to remove extra space & add proper label for box.

![image](https://user-images.githubusercontent.com/75515088/183899715-59cdaf0c-4e85-43f7-9bdc-e3d172d6ab75.png)

**Comment by kaushikpokal** [comment]
spacing issue fixed
add title is developer issue.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed .
Spacing issue is remove from the box.

Now label issue is remaining at developer site.

**Comment by mistry-jignesh** [comment]
I have enabled the below 2 options.


![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/69a25a35-2714-4050-99c9-7f59cb2593bf)

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/50a85da1-e8b9-4d86-8880-60ab66773bdc)

 **Use profile icon is missing on the page**

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/f379f36f-0b57-46f5-af26-f6590e52a249)

**Comment by patel-nimesh** [comment]
Now the user profile is displaying on add page
![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/121149500/19175eea-6f09-4c15-acc2-02360358010c)
![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/121149500/42d881f8-cdab-4b62-a00d-91c643a100f5)
