### ISSUE TITLE
Event details page -  Venue/Organizer section - Remove Biographical Info

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#54]
**Event details page**   - Remove Biographical Info from the Venue/Organizer section.

![image](https://user-images.githubusercontent.com/75515088/184291749-6d30c7ac-4b30-4a9f-bc91-b23f6a3c9cd6.png)

Also Venue/Organizer page section same details ( **Biographical Info)** information is availabel.

![image](https://user-images.githubusercontent.com/75515088/184294280-99334231-6bb7-435a-8999-eab69575bb6c.png)

**Comment by ritakikani** [comment]
@mistry-jignesh  this is not showing in venue and organizer .

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/25837982/86ced65b-c5a3-4095-9567-bd8ebaffa1d8)

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this issue is working fine.
 Biographical Info is removed. So I closed the issue.
