### ISSUE TITLE
In the elementor - URL image size is not change.

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#58]
In the elementor - URL image size is not change.

![image](https://user-images.githubusercontent.com/75515088/187183165-a55bc803-ead7-4a72-8ffb-97bd6a949d44.png)

**Comment by ritakikani** [comment]
This is working fine please verify again.

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now it is working fine.
So I closed the issue.
