### ISSUE TITLE
Need to remove autoupdater folder

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-user-profile-avatar#59]
Need to remove autoupdater folder

<img width="969" alt="Screenshot 2022-08-29 at 18 36 36" src="https://user-images.githubusercontent.com/15089059/187250644-b19337e8-3acc-44b8-89e2-96398bdbcfb6.png">

Need to remove active licesnse

<img width="1558" alt="Screenshot 2022-08-29 at 18 39 00" src="https://user-images.githubusercontent.com/15089059/187251148-9c454352-041d-4bf3-b98f-f225e19b4e63.png">

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now the above suggestions are removed.
This issue is fixed. So I closed the issue.
