### ISSUE TITLE
Need user Profile menu and under all options

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-user-profile-avatar#60]
Need user Profile menu and under all options

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now under user profile menu options are available.

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/681d3180-6c9c-4c78-92ac-d1b388ab114e)

This issue is fixed. So I closed the issue.
