### ISSUE TITLE
Allow Contributors & Subscribers to upload avatars

### ISSUE THREAD

**Issue by sapnadudhat03** [wpeventmanager/wp-user-profile-avatar#7]
It seems like the option "Allow Contributors & Subscribers to upload avatars" is not working.

Doesn't matter whether I enabled or disabled this option, nothing happens for the contributor. It is showing error "**Sorry, you are not allowed to upload files**"...

https://tinyurl.com/yd3g8mhh
![Unbenannt](https://user-images.githubusercontent.com/49863477/82228845-f4eb6d80-9929-11ea-95ba-e69ffccbbc1d.png)

**Comment by sapnadudhat03** [comment]
For subscribers, how can they change the avatar? I didn't find any option on frontend..

**Comment by sapnadudhat03** [comment]
It is working fine now for contributor..

But... **For subscribers, how can they change the avatar? I didn't find any option on frontend..**

**Comment by wpem-kishan** [comment]
@sapnadudhat03 I have checked both side working .
