### ISSUE TITLE
Undefined class error

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-user-profile-avatar#71]
Got error while try to update username from adminpanel

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/25837982/06e30ea6-aae9-4790-9cfd-083946f07104)

**Comment by ritakikani** [comment]
After update username, got error,

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/25837982/e997c43f-5b49-4b1c-9c48-d5095f4c9c9d)

**Comment by mistry-jignesh** [comment]
I have verified this issue .Now this issue is fixed.
Error messge is not display . So I closed the issue.
