### ISSUE TITLE
Media files from other users are not displayed

### ISSUE THREAD

**Issue by martin-roessler** [wpeventmanager/wp-user-profile-avatar#75]
On the Media Library it only shows the images of the current user, either the User is Admin or Editor etc.

Maybe this is infected by the function `wpb_show_current_user_attachments` ?

URL: https://wordpress.org/support/topic/new-update-hides-media-files-in-grid-mode/

**Comment by vijayrathod245** [comment]
On our end, everything is working fine, but we need to check what's happening on the client's end.

**Comment by martin-roessler** [comment]
Hi @vijayrathod245 
This bug should coming, if another another user has been uploaded images to the media library. These images or files are invisible then for another current logged in user. Or did i misundestud you question? :)

**Comment by vijayrathod245** [comment]
It would be helpful if you could share your login details for the site.

**Comment by martin-roessler** [comment]
Hey, its a client site, but maybe you see it in a testsytem with two users - files of other users are "invisible" in grid-mode. :)
Greetings

**Comment by mistry-jignesh** [comment]
Now this issue is fixed. So I closed the issue.
