### ISSUE TITLE
How to disable author bio section from displaying automatically

### ISSUE THREAD

**Issue by troyvassalotti** [wpeventmanager/wp-user-profile-avatar#78]
I found that the author bio section was being added to the post content of a website I'm working on and I need to disable that feature. I found the `wp-author-box-social-info.php` was the culprit, specifically `add_action('the_content', 'wp_author_social_info_box)` and added my own function to _remove_ that action.

Ideally, this would be something I can handle in the admin area, _not_ with custom code. Am I missing a setting that turns this on/off or is my approach of removing that action the only way around it?

**Comment by mistry-jignesh** [comment]
Now our Dev team has added a hide bio info box Avatar option . By default, it is enabled.
If a user wants to disable bio info author box then check mark option and click on the save changes button.
Observed that author box is removed from the post.
![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/3c7d5803-1784-42d0-bbb2-45be9a5979b6)
