### ISSUE TITLE
After refresh the page new profile is visible

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#86]
Create a new page using below shrotcode.

[user_profile_avatar_upload]

Now view page.
  
Add profile image as URL .

Click on the update profile button.

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/e0245ee0-fdc6-4c8e-a485-c5c173d25561)

Observed that After refresh the page new profile is visible.

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/de43f9a1-9aee-4dc7-80fc-f139fb651978)

**Comment by live-aamir** [comment]
@mistry-jignesh This issue is fixed in https://github.com/wpeventmanager/wp-user-profile-avatar/issues/107. Please check.

**Comment by RHSRSK** [comment]
This issue is fixed while solve #109 this issue.

**Comment by mistry-jignesh** [comment]
I have verified the issue. 
Now new profile image is not visible after refreshing the page.
So I closed the issue.
