### ISSUE TITLE
Warning: Undefined array key messasge is display

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#88]
First, create a user on the admin side.

Selected avatar image as below option.

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/31445c14-065c-4bd2-a8b0-306ab053bee6)

Now login into the user account.

Created a new organizer .

Now view the organizer. Here below error message is displayed.

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/36bf0a5f-31d2-47a3-b6ea-2e0324606a36)

**Comment by live-aamir** [comment]
@mistry-jignesh No such error is found. Please check. Below is the screenshot.
![Screenshot_1](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/49248762/fa4c5852-210b-481d-bb8f-d3600e870b0a)

**Comment by mistry-jignesh** [comment]
I have verified it with a new version. Now it is working fine.
A warning message is not available. So I closed the issue.
