### ISSUE TITLE
Elementor :  WP User profile avatar - For all user same image is display

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#93]
Elementor :  WP User profile avatar - For all users same image is display.

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/54cf0e24-77a1-4323-869c-36b0bc377768)

it should be displayed below the image.

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/4f69747d-60e3-4075-8cd6-d8e43bbd01a1)

**Comment by RHSRSK** [comment]
This issue is same as #50 So it fixed there in #50

**Comment by mistry-jignesh** [comment]
This issue is covered in the #50 issue. This issue is fixed.
So I closed the issue.
