### ISSUE TITLE
Elementor : WP User profile avatar  - Open link new window option set as hide then new window is open

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#94]
WP User profile avatar  - Open link new window option set as hide then new window is open.

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/6ea60b42-310f-418f-a709-cb2a8b23ec25)

**Comment by live-aamir** [comment]
@mistry-jignesh Thi issue is working properly. Please check.

**Comment by mistry-jignesh** [comment]
When I have turn off or turn on open a new window option and then click on the user profile icon it displays message  "This site can’t be reached" 


https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/1e04b919-4320-4a79-bbde-131c61a04895

**Comment by RHSRSK** [comment]
This issue is solve within #51 Now it's working properly.

**Comment by mistry-jignesh** [comment]
This issue is covered in the #51 issue. This is working fine with the elementor.
So I closed the issue.
