### ISSUE TITLE
Elementor : WP User profile avatar - Avatar link to set any option then image is display

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#95]
Elementor : WP User profile avatar - Avatar link to set any option then image is display.

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/b0a9fad7-ca75-485c-ab5b-816ed2302ce2)

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/0ebda34f-ebd2-4e21-a57f-4c2e38c6b2c8)

**Comment by RHSRSK** [comment]
This is working properly, Image is loaded when widget is added without choose any link options

[Edit _Elementor Test_ with Elementor.webm](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/126595044/b49cf1db-e572-4cd4-b2ef-32502312b9c9)

**Comment by mistry-jignesh** [comment]
This is working properly, Image is loaded when widget is added without choose any link options.
So I closed the issue.
