### ISSUE TITLE
Need to add space between 2 button

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#96]
Need to add space between 2 buttons.

For that use the below shortcode.

[user_profile_avatar_upload]

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/7a104bb5-ab19-411f-a2bd-b4d7b92a1c67)

**Comment by RHSRSK** [comment]
![Screenshot 2024-07-02 171236](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/126595044/d9aeb448-6f19-4d0e-8161-43f309251a92)

**Comment by mistry-jignesh** [comment]
I have verified this issue. This issue is fixed.
Now space is between 2 buttons.

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/c5213f53-689a-41f2-a288-bf21df682746)

So I closed the issue.
