### ISSUE TITLE
Select avatar size is select large then WP User Profile Avatar section image is display large

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#98]
First, select the below option.

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/74341124-8dd2-4c27-abf8-f5a3fe6580e1)

Now create a page and add a shortcode.

[user_profile_avatar size="large" ]

Go to user profile > profile section

Observed that the WP User Profile Avatar section image is displayed large.

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/c056c6ed-e7e4-4a2a-badc-8c01af5360ab)

**Comment by live-aamir** [comment]
@mistry-jignesh This is working fine. Below is the screencast. Please check.

https://github.com/wpeventmanager/wp-user-profile-avatar/assets/49248762/91f9b0d0-8d7c-4cc5-bf26-879bf42a8d75

**Comment by mistry-jignesh** [comment]
I have verified this issue. 
Now WP User Profile Avatar section image is not displayed large. It is working fine.

![image](https://github.com/wpeventmanager/wp-user-profile-avatar/assets/75515088/e4b17f09-7849-433a-ac9f-0c7069c661fe)

So I closed the issue.
